Update preprocessor.py
Added encoding option when loading the wv from the path.
Ran into issues when loading the downloaded word vectors in a Windows environment (works fine in MAC)
After setting the encoding to UTF-8, I was able to load the word vectors just fine

Line of code I ran from your NER example:
model = text.sequence_tagger('bilstm-crf', preproc)

Windows Environment:
tensorflow 1.14
keras 2.2.4

Error Message:
pretrained word2vec word embeddings will be used with bilstm-crf
Loading pretrained word vectors...this may take a few moments...
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-13-3af5c715b762> in <module>
----> 1 model = text.sequence_tagger('bilstm-crf', preproc)

C:\ProgramData\Anaconda3\lib\site-packages\ktrain\text\ner\models.py in sequence_tagger(name, preproc, word_embedding_dim, char_embedding_dim, word_lstm_size, char_lstm_size, fc_dim, dropout, verbose)
     56         if verbose: print('pretrained %s word embeddings will be used with bilstm-crf' % (preproc.e))
     57         word_embedding_dim = 300
---> 58         emb_dict = tpp.load_wv(verbose=verbose)
     59         emb_model = filter_embeddings(emb_dict, preproc.p._word_vocab.vocab, word_embedding_dim)
     60 

C:\ProgramData\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py in load_wv(wv_path, verbose)
     55     if verbose: print('Loading pretrained word vectors...this may take a few moments...')
     56     if wv_path is None: wv_path = get_wv_path()
---> 57     embeddings_index = dict(get_coefs(*o.rstrip().rsplit(' ')) for o in open(wv_path))
     58     if verbose: print('Done.')
     59     return embeddings_index

C:\ProgramData\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py in <genexpr>(.0)
     55     if verbose: print('Loading pretrained word vectors...this may take a few moments...')
     56     if wv_path is None: wv_path = get_wv_path()
---> 57     embeddings_index = dict(get_coefs(*o.rstrip().rsplit(' ')) for o in open(wv_path))
     58     if verbose: print('Done.')
     59     return embeddings_index

C:\ProgramData\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7674: character maps to <undefined>